<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }

final class Newsroom_Bridge_Publish_REST {
	private $auth; private $drafts; private $draft_db; private $transaction_starter;
	public function __construct(Newsroom_Bridge_Publish_Auth $auth,Newsroom_Bridge_Draft_Sync_REST $drafts,Newsroom_Bridge_DB $draft_db,$transaction_starter=null){$this->auth=$auth;$this->drafts=$drafts;$this->draft_db=$draft_db;$this->transaction_starter=$transaction_starter;}
	public function register_routes(){register_rest_route('newsroom/v1','/publications',array('methods'=>'POST','callback'=>array($this,'publish'),'permission_callback'=>array($this->auth,'permission_check')));register_rest_route('newsroom/v1','/publications/(?P<publish_key>[a-f0-9-]{36})',array('methods'=>'GET','callback'=>array($this,'get'),'permission_callback'=>array($this->auth,'permission_check')));}
	public function get(WP_REST_Request $r){$key=(string)$r['publish_key'];if(!$this->uuid($key))return $this->bad('newsroom_invalid_publish_key',400);$ready=Newsroom_Bridge_Publications_Table::verify();if(is_wp_error($ready))return $ready;global $wpdb;$row=$wpdb->get_row($wpdb->prepare('SELECT publish_key,draft_key,post_id,expected_applied_version,status,published_at FROM '.Newsroom_Bridge_Publications_Table::name().' WHERE publish_key=%s',$key),ARRAY_A);if(!$row)return new WP_Error('newsroom_publication_not_found','Publication ledger entry was not found.',array('status'=>404));return new WP_REST_Response($this->ledger($row),200);}
	public function publish(WP_REST_Request $r){$input=$r->get_json_params();$allowed=array('publish_key','draft_key','expected_applied_version','post_id');if(!is_array($input)||wp_is_numeric_array($input)||array_values(array_diff(array_keys($input),$allowed))||count($input)!==4||!$this->uuid($input['publish_key']??null)||!$this->uuid($input['draft_key']??null)||!is_string($input['expected_applied_version']??null)||!preg_match('/\A[0-9a-f]{64}\z/D',$input['expected_applied_version'])||!is_int($input['post_id']??null)||$input['post_id']<1)return $this->bad('newsroom_invalid_payload',400);
		$ready=Newsroom_Bridge_Publications_Table::verify();if(is_wp_error($ready))return $ready;$draft_ready=$this->draft_db->assert_ready_and_transactional();if(is_wp_error($draft_ready))return $draft_ready;global $wpdb;$table=Newsroom_Bridge_Publications_Table::name();$started=is_callable($this->transaction_starter)?call_user_func($this->transaction_starter):$wpdb->query('START TRANSACTION');if(false===$started)return new WP_Error('newsroom_publication_storage_error','Publication could not be completed.',array('status'=>503));$committed=false;
		try{$row=$wpdb->get_row($wpdb->prepare("SELECT publish_key,draft_key,post_id,expected_applied_version,status,published_at FROM {$table} WHERE publish_key=%s FOR UPDATE",$input['publish_key']),ARRAY_A);if($row){if($this->binding($row,$input)&&'PUBLISHED'===$row['status']){$wpdb->query('COMMIT');$committed=true;wp_cache_delete($input['post_id'],'posts');return new WP_REST_Response($this->success($row),200);}throw new Newsroom_Publish_Failure('newsroom_publication_conflict','STATE_MISMATCH');}
			$map=$this->draft_db->get_for_update($input['draft_key']);if(!is_array($map)||null!==$map['reservation_token']||(int)$map['post_id']!==$input['post_id']||(int)$map['actor_user_id']!==(int)NEWSROOM_BRIDGE_USER_ID)throw new Newsroom_Publish_Failure('newsroom_publication_state_mismatch','STATE_MISMATCH');
			$before_row=$wpdb->get_row($wpdb->prepare("SELECT * FROM {$wpdb->posts} WHERE ID=%d FOR UPDATE",$input['post_id']),ARRAY_A);if(!is_array($before_row)||'post'!==$before_row['post_type']||'draft'!==$before_row['post_status']||(int)$before_row['post_author']!==(int)NEWSROOM_BRIDGE_USER_ID)throw new Newsroom_Publish_Failure('newsroom_publication_state_mismatch','STATE_MISMATCH');$before=$this->drafts->managed_state($input['post_id'],'draft',true);if(!hash_equals($input['expected_applied_version'],$this->drafts->canonical_state_fingerprint($before)))throw new Newsroom_Publish_Failure('newsroom_publication_stale_version','STALE_VERSION');$now=current_time('mysql',true);
			$insert=$wpdb->query($wpdb->prepare("INSERT INTO {$table} (publish_key,draft_key,post_id,expected_applied_version,status,published_at,created_at,updated_at) VALUES (%s,%s,%d,%s,'RESERVED',NULL,%s,%s)",$input['publish_key'],$input['draft_key'],$input['post_id'],$input['expected_applied_version'],$now,$now));if(1!==$insert)throw new RuntimeException('reserve_failed');
			$updated=$wpdb->query($wpdb->prepare("UPDATE {$wpdb->posts} SET post_status='publish' WHERE ID=%d AND post_type='post' AND post_status='draft' AND post_author=%d",$input['post_id'],NEWSROOM_BRIDGE_USER_ID));if(1!==$updated)throw new Newsroom_Publish_Failure('newsroom_publication_state_mismatch','STATE_MISMATCH');$after_row=$wpdb->get_row($wpdb->prepare("SELECT * FROM {$wpdb->posts} WHERE ID=%d",$input['post_id']),ARRAY_A);$after=$this->drafts->managed_state($input['post_id'],'publish',true);$expected_row=$before_row;$expected_row['post_status']='publish';if($after_row!==$expected_row||$this->drafts->canonical_state_fingerprint($after)!==$input['expected_applied_version']||$before['author_id']!==$after['author_id']||$before['thumbnail_id']!==$after['thumbnail_id'])throw new RuntimeException('postcondition_failed');
			$done=$wpdb->query($wpdb->prepare("UPDATE {$table} SET status='PUBLISHED',published_at=%s,updated_at=%s WHERE publish_key=%s AND status='RESERVED'",$now,$now,$input['publish_key']));if(1!==$done)throw new RuntimeException('ledger_finalize_failed');if(false===$wpdb->query('COMMIT'))throw new RuntimeException('commit_failed');$committed=true;wp_cache_delete($input['post_id'],'posts');return new WP_REST_Response(array('publish_key'=>$input['publish_key'],'post_id'=>$input['post_id'],'status'=>'publish','applied_version_before'=>$input['expected_applied_version'],'published_at'=>$now),200);
		}catch(Newsroom_Publish_Failure $e){if(!$committed)$wpdb->query('ROLLBACK');return new WP_Error($e->getMessage(),$e->public_code,array('status'=>409));}catch(Throwable $e){if(!$committed)$wpdb->query('ROLLBACK');return new WP_Error('newsroom_publication_storage_error','Publication could not be completed.',array('status'=>503));}}
	private function binding($r,$i){return $r['draft_key']===$i['draft_key']&&(int)$r['post_id']===$i['post_id']&&$r['expected_applied_version']===$i['expected_applied_version'];}
	private function ledger($r){return array('publish_key'=>$r['publish_key'],'draft_key'=>$r['draft_key'],'post_id'=>(int)$r['post_id'],'expected_applied_version'=>$r['expected_applied_version'],'status'=>$r['status'],'published_at'=>$r['published_at']);}
	private function success($r){return array('publish_key'=>$r['publish_key'],'post_id'=>(int)$r['post_id'],'status'=>'publish','applied_version_before'=>$r['expected_applied_version'],'published_at'=>$r['published_at']);}
	private function uuid($v){return is_string($v)&&1===preg_match('/\A[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\z/D',$v)&&wp_is_uuid($v,4);}
	private function bad($c,$s){return new WP_Error($c,'Invalid publication request.',array('status'=>$s));}
}
final class Newsroom_Publish_Failure extends RuntimeException {public $public_code;public function __construct($code,$public){parent::__construct($code);$this->public_code=$public;}}
