<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }

final class Newsroom_Bridge_Publish_Auth {
	private const VERSION='newsroom-publish-hmac-v1'; private const CAP='publish_newsroom_publications'; private const SKEW=300;
	private $keys=array(); private $users=array(); private $proof=null; private $candidate=null; private $active=false; private $early_conflict=false;
	public function __construct() {
		if(!defined('NEWSROOM_BRIDGE_PUBLISH_HMAC_KEYS_JSON')||!defined('NEWSROOM_BRIDGE_PUBLISHER_USERS_JSON'))return;
		$entries=Newsroom_Bridge_Key_Ring_JSON::parse(NEWSROOM_BRIDGE_PUBLISH_HMAC_KEYS_JSON);$users=json_decode(NEWSROOM_BRIDGE_PUBLISHER_USERS_JSON,true);
		if(!is_array($entries)||!is_array($users))return;
		foreach($entries as $e){if(!is_array($e)||count($e)!==2||!isset($e['id'],$e['secret'])||!preg_match('/\A[a-z0-9][a-z0-9._-]{0,63}\z/D',$e['id'])||isset($this->keys[$e['id']])||!preg_match('/\A[A-Za-z0-9_-]{43}\z/D',$e['secret'])){$this->keys=array();return;}$d=base64_decode(strtr($e['secret'],'-_','+/').'=',true);if(!is_string($d)||strlen($d)!==32||rtrim(strtr(base64_encode($d),'+/','-_'),'=')!==$e['secret']){$this->keys=array();return;}$this->keys[$e['id']]=$d;}
		foreach($users as $k=>$v){if(!isset($this->keys[$k])||(!is_int($v)&&!(is_string($v)&&preg_match('/\A[1-9][0-9]*\z/D',$v)))||(int)$v<1){$this->users=array();return;}$this->users[$k]=(int)$v;} if(count($this->users)!==count($this->keys)){$this->keys=array();$this->users=array();}
	}
	public function register(){add_filter('rest_allowed_cors_headers',array($this,'capture'),PHP_INT_MIN,2);add_filter('rest_authentication_errors',array($this,'snapshot_conflict'),PHP_INT_MIN);add_filter('rest_authentication_errors',array($this,'authenticate'),120);add_filter('rest_endpoints',array($this,'wrap'),PHP_INT_MAX);}
	public function capture($h,$r=null){if($r instanceof WP_REST_Request)$this->candidate=$r;return $h;}
	public static function is_route($method,$route){return ('POST'===$method&&'/newsroom/v1/publications'===$route)||('GET'===$method&&1===preg_match('#\A/newsroom/v1/publications/[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\z#D',$route));}
	public static function has_draft_headers(){foreach(array('HTTP_X_NEWSROOM_AUTH_VERSION','HTTP_X_NEWSROOM_KEY_ID','HTTP_X_NEWSROOM_TIMESTAMP','HTTP_X_NEWSROOM_SIGNATURE') as $h)if(array_key_exists($h,$_SERVER))return true;return false;}
	public function authenticate($result){$route=$this->external_route();$method=isset($_SERVER['REQUEST_METHOD'])?strtoupper((string)$_SERVER['REQUEST_METHOD']):'';$any=$this->has_publish_headers();if(!$any&&!self::is_route($method,$route))return $result;
		if(!self::is_route($method,$route))return $this->fail(401,'route');if(self::has_draft_headers())return $this->fail(401,'draft');if($this->has_media_headers())return $this->fail(401,'media');if($this->has_authorization())return $this->fail(401,'authorization');if(get_current_user_id()>0)return $this->fail(401,'user');if($this->early_conflict||is_wp_error($result)||(null!==$result&&false!==$result&&true!==$result))return $this->fail(401,'prior');if(empty($this->keys))return $this->fail(401,'configuration');
		if(isset($_SERVER['HTTP_X_HTTP_METHOD_OVERRIDE'])||isset($_GET['_method'])||isset($_POST['_method'])||null!==wp_parse_url((string)$_SERVER['REQUEST_URI'],PHP_URL_QUERY))return $this->fail(401,'request');
		$v=$this->singleton('HTTP_X_NEWSROOM_PUBLISH_AUTH_VERSION');$k=$this->singleton('HTTP_X_NEWSROOM_PUBLISH_KEY_ID');$ts=$this->singleton('HTTP_X_NEWSROOM_PUBLISH_TIMESTAMP');$sig=$this->singleton('HTTP_X_NEWSROOM_PUBLISH_SIGNATURE');if(self::VERSION!==$v||!isset($this->keys[$k],$this->users[$k])||!preg_match('/\A[0-9]{10,12}\z/D',(string)$ts)||abs((int)$ts-time())>self::SKEW||!preg_match('/\A[A-Za-z0-9_-]{43}\z/D',(string)$sig))return $this->fail(401,'headers');
		$body=file_get_contents('php://input');if(false===$body||('GET'===$method&&''!==$body))return $this->fail(401,'body');$canonical=implode("\n",array(self::VERSION,$k,$method,$route,$ts,hash('sha256',$body)));$expected=rtrim(strtr(base64_encode(hash_hmac('sha256',$canonical,$this->keys[$k],true)),'+/','-_'),'=');if(!hash_equals($expected,$sig))return $this->fail(401,'signature');$u=get_user_by('id',$this->users[$k]);if(!$u||!user_can($this->users[$k],self::CAP))return $this->fail(403,'capability');$this->proof=array('request'=>$this->candidate,'method'=>$method,'route'=>$route,'user'=>$this->users[$k]);return true;}
	public function permission_check($request){return $this->matches($request);}
	public function wrap($endpoints){foreach(array('/newsroom/v1/publications','/newsroom/v1/publications/(?P<publish_key>[a-f0-9-]{36})') as $route){if(!isset($endpoints[$route]))continue;foreach($endpoints[$route] as &$h){if(!is_array($h)||!isset($h['callback'],$h['permission_callback'])||!is_array($h['permission_callback'])||$h['permission_callback'][0]!==$this)continue;$cb=$h['callback'];$h['callback']=function($r)use($cb){if(!$this->matches($r)||$this->active)return new WP_Error('newsroom_publish_execution_binding_failed','Newsroom publication authentication failed.',array('status'=>401));$old=get_current_user_id();try{$this->active=true;wp_set_current_user($this->proof['user']);return call_user_func($cb,$r);}finally{wp_set_current_user($old);$this->active=false;$this->proof=null;}};}unset($h);}return $endpoints;}
	private function matches($request){return is_array($this->proof)&&$request instanceof WP_REST_Request&&$request->get_method()===$this->proof['method']&&$request->get_route()===$this->proof['route'];}
	private function external_route(){global $wp;if(!isset($wp->query_vars['rest_route']))return '';$r=(string)$wp->query_vars['rest_route'];$path=wp_parse_url((string)$_SERVER['REQUEST_URI'],PHP_URL_PATH);$base=wp_parse_url(rest_url(),PHP_URL_PATH);return is_string($path)&&is_string($base)&&$path===rtrim($base,'/').$r?$r:'';}
	private function singleton($n){if(!array_key_exists($n,$_SERVER)||!is_string($_SERVER[$n])||strpos($_SERVER[$n],',')!==false)return null;return wp_unslash($_SERVER[$n]);}
	private function has_publish_headers(){foreach(array('HTTP_X_NEWSROOM_PUBLISH_AUTH_VERSION','HTTP_X_NEWSROOM_PUBLISH_KEY_ID','HTTP_X_NEWSROOM_PUBLISH_TIMESTAMP','HTTP_X_NEWSROOM_PUBLISH_SIGNATURE')as$h)if(array_key_exists($h,$_SERVER))return true;return false;}
	public function snapshot_conflict($result){if($this->has_publish_headers())$this->early_conflict=$this->early_conflict||get_current_user_id()>0||$this->has_authorization()||(null!==$result&&false!==$result);return $result;}
	private function has_media_headers(){foreach(array_keys($_SERVER)as$h)if(0===strpos($h,'HTTP_X_NEWSROOM_MEDIA_'))return true;return false;}
	private function has_authorization(){foreach(array('HTTP_AUTHORIZATION','REDIRECT_HTTP_AUTHORIZATION') as $name){if(array_key_exists($name,$_SERVER)&&(!is_string($_SERVER[$name])||''!==$_SERVER[$name]))return true;}foreach(array('AUTH_COOKIE','SECURE_AUTH_COOKIE','LOGGED_IN_COOKIE') as $constant){if(defined($constant)&&array_key_exists(constant($constant),$_COOKIE))return true;}return false;}
	private function fail($status=401,$reason=''){unset($reason);$this->proof=null;return new WP_Error('newsroom_publish_authentication_failed','Newsroom publication authentication failed.',array('status'=>$status));}
}
