import { normalizeWordPressBaseUrl, SecureWordPressTransport, WordPressTransportSecurityError, type WordPressTransportResponse } from "../wordpress-transport/wordpress-secure-transport";
import { assertPublicationRoute, decodePublicationSecret, signPublicationRequest } from "./wordpress-publication-hmac";

const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/; const SHA=/^[0-9a-f]{64}$/;
export type PublicationIntent={publishKey:string;draftKey:string;postId:number;expectedAppliedVersion:string};
export type PublishedEvidence={outcome:"PUBLISHED";publishKey:string;postId:number;status:"publish";appliedVersionBefore:string;publishedAt:string};
export type LedgerEvidence={outcome:"PUBLISHED"|"RESERVED";publishKey:string;draftKey:string;postId:number;expectedAppliedVersion:string;publishedAt:string|null};
export type PublicationOutcome=LedgerEvidence|{outcome:"NOT_FOUND"};
export type PublicationErrorCode="STALE_VERSION"|"STATE_MISMATCH"|"AUTHORITY_BLOCKED"|"RECONCILIATION_REQUIRED"|"UNCERTAIN_OUTCOME"|"CONTRACT_FAILURE";
export class WordPressPublicationError extends Error{constructor(public readonly code:PublicationErrorCode,message:string,public readonly status?:number){super(message);}}
export interface PublicationTransport{send(request:{method:"GET"|"POST";url:string;headers:Readonly<Record<string,string>>;body?:string;timeoutMs:number}):Promise<WordPressTransportResponse>}
export class WordPressPublicationClient{
  private readonly base:URL;private readonly secret:Buffer;private readonly transport:PublicationTransport;
  constructor(private readonly options:{baseUrl:string;keyId:string;secret:string;requestTimeoutMs:number},transport?:PublicationTransport,private readonly now:()=>number=()=>Date.now()){this.base=normalizeWordPressBaseUrl(options.baseUrl);if(!/^[a-z0-9][a-z0-9._-]{0,63}$/.test(options.keyId)||!Number.isInteger(options.requestTimeoutMs)||options.requestTimeoutMs<100)throw new Error("Invalid WordPress publication client configuration.");this.secret=decodePublicationSecret(options.secret);this.transport=transport??new SecureWordPressTransport();}
  async get(publishKey:string):Promise<PublicationOutcome>{if(!UUID.test(publishKey))throw new WordPressPublicationError("CONTRACT_FAILURE","Invalid publish key.");const response=await this.send("GET",`/newsroom/v1/publications/${publishKey}`);if(response.status===404)return{outcome:"NOT_FOUND"};if(response.status!==200)throw classify(response);return ledger(response.body,publishKey);}
  async publish(input:PublicationIntent):Promise<PublishedEvidence>{validate(input);const body=JSON.stringify({publish_key:input.publishKey,draft_key:input.draftKey,expected_applied_version:input.expectedAppliedVersion,post_id:input.postId});try{const response=await this.send("POST","/newsroom/v1/publications",body);if(response.status!==200)throw classify(response);return success(response.body,input);}catch(error){const failure=error instanceof WordPressPublicationError?error:new WordPressPublicationError("UNCERTAIN_OUTCOME","Publication outcome is uncertain.");if(failure.code!=="UNCERTAIN_OUTCOME")throw failure;let found:PublicationOutcome;try{found=await this.get(input.publishKey);}catch{throw failure;}if(found.outcome==="PUBLISHED"){if(found.draftKey!==input.draftKey||found.postId!==input.postId||found.expectedAppliedVersion!==input.expectedAppliedVersion)throw new WordPressPublicationError("RECONCILIATION_REQUIRED","Publication ledger binding conflicts.");return{outcome:"PUBLISHED",publishKey:found.publishKey,postId:found.postId,status:"publish",appliedVersionBefore:found.expectedAppliedVersion,publishedAt:found.publishedAt as string};}if(found.outcome==="RESERVED")throw new WordPressPublicationError("RECONCILIATION_REQUIRED","Publication is reserved.");throw failure;}}
  private async send(method:"GET"|"POST",route:string,body=""):Promise<WordPressTransportResponse>{assertPublicationRoute(method,route);const headers:Record<string,string>={...signPublicationRequest({keyId:this.options.keyId,secret:this.secret,method,route,timestamp:Math.floor(this.now()/1000),rawBody:body})};if(method==="POST")headers["Content-Type"]="application/json";const url=new URL(this.base);url.pathname=`${url.pathname==="/"?"":url.pathname}/wp-json${route}`;try{return await this.transport.send({method,url:url.toString(),headers,...(method==="POST"?{body}:{}),timeoutMs:this.options.requestTimeoutMs});}catch(e){if(e instanceof WordPressTransportSecurityError)throw new WordPressPublicationError("CONTRACT_FAILURE","Transport policy rejected publication.");throw new WordPressPublicationError("UNCERTAIN_OUTCOME","Publication outcome is uncertain.");}}
}
function validate(i:PublicationIntent):void{if(!UUID.test(i.publishKey)||!UUID.test(i.draftKey)||!Number.isSafeInteger(i.postId)||i.postId<1||!SHA.test(i.expectedAppliedVersion))throw new WordPressPublicationError("CONTRACT_FAILURE","Invalid publication intent.");}
function object(v:unknown):Record<string,unknown>{if(!v||typeof v!=="object"||Array.isArray(v))throw new WordPressPublicationError("CONTRACT_FAILURE","Malformed publication response.");return v as Record<string,unknown>;}
function ledger(body:unknown,key:string):LedgerEvidence{const v=object(body);if(JSON.stringify(Object.keys(v).sort())!==JSON.stringify(["draft_key","expected_applied_version","post_id","publish_key","published_at","status"])||v.publish_key!==key||!UUID.test(String(v.draft_key))||!Number.isSafeInteger(v.post_id)||!SHA.test(String(v.expected_applied_version))||(v.status!=="PUBLISHED"&&v.status!=="RESERVED")||(v.status==="PUBLISHED"&&typeof v.published_at!=="string")||(v.status==="RESERVED"&&v.published_at!==null))throw new WordPressPublicationError("CONTRACT_FAILURE","Malformed publication response.");return{outcome:v.status,publishKey:key,draftKey:String(v.draft_key),postId:v.post_id as number,expectedAppliedVersion:String(v.expected_applied_version),publishedAt:v.published_at as string|null};}
function success(body:unknown,i:PublicationIntent):PublishedEvidence{const v=object(body);if(JSON.stringify(Object.keys(v).sort())!==JSON.stringify(["applied_version_before","post_id","publish_key","published_at","status"])||v.publish_key!==i.publishKey||v.post_id!==i.postId||v.status!=="publish"||v.applied_version_before!==i.expectedAppliedVersion||typeof v.published_at!=="string")throw new WordPressPublicationError("CONTRACT_FAILURE","Malformed publication response.");return{outcome:"PUBLISHED",publishKey:i.publishKey,postId:i.postId,status:"publish",appliedVersionBefore:i.expectedAppliedVersion,publishedAt:v.published_at};}
function classify(r:WordPressTransportResponse):WordPressPublicationError{if(r.status>=500)return new WordPressPublicationError("UNCERTAIN_OUTCOME","Publication outcome is uncertain.",r.status);const response=object(r.body);const code=response.code;const publicCode=response.message;if(r.status===409&&publicCode==="STALE_VERSION")return new WordPressPublicationError("STALE_VERSION","Publication version is stale.",409);if(r.status===409)return new WordPressPublicationError(code==="newsroom_publication_conflict"?"RECONCILIATION_REQUIRED":"STATE_MISMATCH","Publication state mismatched.",409);if(r.status===401||r.status===403)return new WordPressPublicationError("AUTHORITY_BLOCKED","Publication authority was denied.",r.status);return new WordPressPublicationError("CONTRACT_FAILURE","Publication contract was rejected.",r.status);}
