/* eslint-disable @typescript-eslint/no-explicit-any, @typescript-eslint/no-unsafe-member-access, @typescript-eslint/no-unsafe-argument, @typescript-eslint/require-await */
import { createHash } from "node:crypto";
import { publicationCanonical, signPublicationRequest } from "./wordpress-publication-hmac";
import { WordPressPublicationClient, WordPressPublicationError, type PublicationTransport } from "./wordpress-publication.client";

const publishKey="123e4567-e89b-42d3-a456-426614174000";const draftKey="223e4567-e89b-42d3-a456-426614174000";const version="a".repeat(64);const secret=Buffer.alloc(32);const encoded=secret.toString("base64url");
describe("WordPress publication authority client",()=>{
  it("matches the frozen GET zero-byte HMAC KAT",()=>{const route=`/newsroom/v1/publications/${publishKey}`;expect(createHash("sha256").update("").digest("hex")).toBe("e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855");expect(publicationCanonical({keyId:"test-publish-key",method:"GET",route,timestamp:1700000000,rawBody:""})).toBe(`newsroom-publish-hmac-v1\ntest-publish-key\nGET\n${route}\n1700000000\ne3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855`);expect(signPublicationRequest({keyId:"test-publish-key",secret,method:"GET",route,timestamp:1700000000,rawBody:""})["X-Newsroom-Publish-Signature"]).toBe("462qV0g0-Oh1VTiudA8hNXjAFTVjD8v2yXVTTkpjf-o");});
  it("sends exact body bytes and singleton publish headers",async()=>{const calls:any[]=[];const transport:PublicationTransport={send:async r=>{calls.push(r);return{status:200,body:{publish_key:publishKey,post_id:9,status:"publish",applied_version_before:version,published_at:"2026-09-13 12:00:00"}};}};const client=new WordPressPublicationClient({baseUrl:"https://wordpress.test",keyId:"test-publish-key",secret:encoded,requestTimeoutMs:5000},transport,()=>1700000000000);await client.publish({publishKey,draftKey,postId:9,expectedAppliedVersion:version});expect(calls[0].body).toBe(JSON.stringify({publish_key:publishKey,draft_key:draftKey,expected_applied_version:version,post_id:9}));expect(Object.keys(calls[0].headers).filter((x:string)=>x.startsWith("X-Newsroom-Publish-"))).toHaveLength(4);});
  it("performs GET before returning an uncertain POST outcome",async()=>{const methods:string[]=[];const transport:PublicationTransport={send:async r=>{methods.push(r.method);if(r.method==="POST")throw new Error("timeout");return{status:404,body:{code:"newsroom_publication_not_found"}};}};const client=new WordPressPublicationClient({baseUrl:"https://wordpress.test",keyId:"test-publish-key",secret:encoded,requestTimeoutMs:5000},transport);await expect(client.publish({publishKey,draftKey,postId:9,expectedAppliedVersion:version})).rejects.toMatchObject<Partial<WordPressPublicationError>>({code:"UNCERTAIN_OUTCOME"});expect(methods).toEqual(["POST","GET"]);});
  it("recovers exact PUBLISHED evidence and rejects RESERVED",async()=>{for(const status of ["PUBLISHED","RESERVED"] as const){const transport:PublicationTransport={send:async r=>{if(r.method==="POST")throw new Error("timeout");return{status:200,body:{publish_key:publishKey,draft_key:draftKey,post_id:9,expected_applied_version:version,status,published_at:status==="PUBLISHED"?"2026-09-13 12:00:00":null}};}};const client=new WordPressPublicationClient({baseUrl:"https://wordpress.test",keyId:"test-publish-key",secret:encoded,requestTimeoutMs:5000},transport);const promise=client.publish({publishKey,draftKey,postId:9,expectedAppliedVersion:version});if(status==="PUBLISHED")await expect(promise).resolves.toMatchObject({outcome:"PUBLISHED"});else await expect(promise).rejects.toMatchObject({code:"RECONCILIATION_REQUIRED"});}});
  it.each([[503,{code:"temporary"}],[503,"plain text"],[502,null]])("reconciles any %i response before returning despite a non-contract body",async(status,postBody)=>{const methods:string[]=[];const transport:PublicationTransport={send:async r=>{methods.push(r.method);return r.method==="POST"?{status,body:postBody}:{status:404,body:{code:"newsroom_publication_not_found"}};}};const client=new WordPressPublicationClient({baseUrl:"https://wordpress.test",keyId:"test-publish-key",secret:encoded,requestTimeoutMs:5000},transport);await expect(client.publish({publishKey,draftKey,postId:9,expectedAppliedVersion:version})).rejects.toMatchObject({code:"UNCERTAIN_OUTCOME",status});expect(methods).toEqual(["POST","GET"]);});
  it.each(["PUBLISHED","RESERVED"] as const)("reconciles a 5xx POST to %s without a second POST",async(status)=>{const methods:string[]=[];const transport:PublicationTransport={send:async r=>{methods.push(r.method);if(r.method==="POST")return{status:503,body:"upstream unavailable"};return{status:200,body:{publish_key:publishKey,draft_key:draftKey,post_id:9,expected_applied_version:version,status,published_at:status==="PUBLISHED"?"2026-09-13 12:00:00":null}};}};const client=new WordPressPublicationClient({baseUrl:"https://wordpress.test",keyId:"test-publish-key",secret:encoded,requestTimeoutMs:5000},transport);const result=client.publish({publishKey,draftKey,postId:9,expectedAppliedVersion:version});if(status==="PUBLISHED")await expect(result).resolves.toMatchObject({outcome:"PUBLISHED"});else await expect(result).rejects.toMatchObject({code:"RECONCILIATION_REQUIRED"});expect(methods).toEqual(["POST","GET"]);});
});
