export const DRAFT_PREPARATION_CODES = [
  "COMPLETENESS_NOT_SATISFIED",
  "CATEGORY_SELECTION_NO_LONGER_ACTIVE",
  "STORY_FINALISATION_CONFLICT",
  "REPORTER_NOT_ACTIVE",
  "MEDIA_OBJECT_STORE_UNCONFIGURED",
  "MEDIA_BYTES_UNAVAILABLE",
  "MEDIA_BYTES_INTEGRITY_FAILURE",
  "WORDPRESS_MEDIA_BLOCKED",
  "WORDPRESS_MEDIA_RECONCILIATION_REQUIRED",
  "WORDPRESS_MEDIA_IDENTITY_CONFLICT",
  "WORDPRESS_DRAFT_BLOCKED",
  "WORDPRESS_DRAFT_RECONCILIATION_REQUIRED",
  "WORDPRESS_DRAFT_IDENTITY_CONFLICT",
  "WORDPRESS_STATE_MISMATCH",
] as const;
export type DraftPreparationCode = (typeof DRAFT_PREPARATION_CODES)[number];
export class DraftPreparationError extends Error {
  constructor(public readonly code: DraftPreparationCode) {
    super(code);
    this.name = "DraftPreparationError";
  }
}
